// src/lib/formationIcons.ts
export type FormationItem = {
  id: string;
  thumb: string;
  svg?: string;
  iconSize?: number;
};


export const FORMATION_GROUPS: Record<string, FormationItem[]> = {
  "Combat Units": [
    { id: "cbt", thumb: "/formations/combat_Units/cbt.png", iconSize: 1 },
    { id: "arc", thumb: "/formations/combat_Units/arc.png", iconSize: 1 },
    { id: "bow", thumb: "/formations/combat_Units/bowtie.png", iconSize: 1 },
    { id: "boxx", thumb: "/formations/combat_Units/x.png", iconSize: 1 },
    { id: "tri", thumb: "/formations/combat_Units/xtri.png", iconSize: 1 },
    { id: "oval", thumb: "/formations/combat_Units/oval.png", iconSize: 1 },
    { id: "dot", thumb: "/formations/combat_Units/dot.png", iconSize: 1 },
    { id: "u", thumb: "/formations/combat_Units/u.png", iconSize: 1 },
    { id: "diag", thumb: "/formations/combat_Units/diag.png", iconSize: 1 },
    { id: "gate", thumb: "/formations/combat_Units/gate.png", iconSize: 1},
    { id: "sec", thumb: "/formations/combat_Units/sec.png", iconSize: 1 },
  ],

  "Combat Support Units": [
    { id: "cs", thumb: "/formations/Combat_Support/cs.png", iconSize: 1.4 },
    { id: "antenna", thumb: "/formations/Combat_Support/antenna.png", iconSize: 1.4 },
    { id: "mi", thumb: "/formations/Combat_Support/mi.png", iconSize: 1.4 },
    { id: "mp", thumb: "/formations/Combat_Support/mp.png", iconSize: 1.4 },
    { id: "diag", thumb: "/formations/Combat_Support/diag.png", iconSize: 1.4 },
    { id: "iw", thumb: "/formations/Combat_Support/iw.png", iconSize: 1.4 },
    { id: "ls", thumb: "/formations/Combat_Support/ls.png", iconSize: 1.4 },
    { id: "eod", thumb: "/formations/Combat_Support/eod.png", iconSize: 1.4 },
  ],

  "Combat Service Support Units": [
    { id: "css", thumb: "/formations/Combat_Service/css.png", iconSize: 1.4 },
    { id: "adm", thumb: "/formations/Combat_Service/adm.png", iconSize: 1.4 },
    { id: "grid", thumb: "/formations/Combat_Service/grid.png", iconSize: 1.4 },
    { id: "hline", thumb: "/formations/Combat_Service/hline.png", iconSize: 1.4 },
    { id: "wheel", thumb: "/formations/Combat_Service/wheel.png", iconSize: 1.4 },
    { id: "link", thumb: "/formations/Combat_Service/link.png", iconSize: 1.4 },
  ],

  "Command and Control": [
    { id: "c2hq", thumb: "/formations/Command_Control/c2hq.png", iconSize: 1.4 },
  ],
  "Infantry": [
    { id: "inf", thumb: "/formations/infantry/inf.png", iconSize: 1},
    { id: "lif inf", thumb: "/formations/infantry/lif inf.png", iconSize: 1 },
    { id: "mot inf", thumb: "/formations/infantry/mot inf.png", iconSize: 1 },
    { id: "mnt inf", thumb: "/formations/infantry/mnt inf.png", iconSize: 1 },
    { id: "abn inf", thumb: "/formations/infantry/abn inf.png", iconSize: 1 },
    { id: "aast inf", thumb: "/formations/infantry/aast inf.png", iconSize: 1 },
    { id: "nav inf", thumb: "/formations/infantry/nav inf.png", iconSize: 1 },
    { id: "mech inf", thumb: "/formations/infantry/mech inf.png", iconSize: 1 },
    { id: "inffv", thumb: "/formations/infantry/inffv.png", iconSize: 1 },
    { id: "arc inf", thumb: "/formations/infantry/arc inf.png", iconSize: 1 },
    { id: "dmd grd isf", thumb: "/formations/infantry/dmd grd isf.png", iconSize: 1 },
  ],

  "Armored / Tracked": [
    { id: "arm_01", thumb: "/formations/armored_tracked/arm_01.png", iconSize: 1 },
    { id: "arm_02", thumb: "/formations/armored_tracked/arm_02.png", iconSize: 1 },
    { id: "arm_03", thumb: "/formations/armored_tracked/arm_03.png", iconSize: 1 },
    { id: "arm_04", thumb: "/formations/armored_tracked/arm_04.png", iconSize: 1 },
    { id: "arm_05", thumb: "/formations/armored_tracked/arm_05.png", iconSize: 1 },
    { id: "arm_06", thumb: "/formations/armored_tracked/arm_06.png", iconSize: 1 },
    { id: "arm_07", thumb: "/formations/armored_tracked/arm_07.png", iconSize: 1 },
    { id: "arm_08", thumb: "/formations/armored_tracked/arm_08.png", iconSize: 1 },
    { id: "arm_09", thumb: "/formations/armored_tracked/arm_09.png", iconSize: 1 },
  ],
  "Artillery": [
    { id: "art_01", thumb: "/formations/artillery/art_01.png", iconSize: 1 },
    { id: "art_02", thumb: "/formations/artillery/art_02.png", iconSize: 1 },
    { id: "art_03", thumb: "/formations/artillery/art_03.png", iconSize: 1 },
    { id: "art_04", thumb: "/formations/artillery/art_04.png", iconSize: 1 },
    { id: "art_05", thumb: "/formations/artillery/art_05.png", iconSize: 1 },
    { id: "art_06", thumb: "/formations/artillery/art_06.png", iconSize: 1 },
    { id: "art_07", thumb: "/formations/artillery/art_07.png", iconSize: 1 },
    { id: "art_08", thumb: "/formations/artillery/art_08.png", iconSize: 1 },
    { id: "art_09", thumb: "/formations/artillery/art_09.png", iconSize: 1 },
    { id: "art_10", thumb: "/formations/artillery/art_10.png", iconSize: 1 },
    { id: "art_11", thumb: "/formations/artillery/art_11.png", iconSize: 1 },
    { id: "art_12", thumb: "/formations/artillery/art_12.png", iconSize: 1 },
  ],
  "Aviation": [
    { id: "avt_01", thumb: "/formations/aviation/avt_01.png", iconSize: 1 },
    { id: "avt_02", thumb: "/formations/aviation/avt_02.png", iconSize: 1 },
    { id: "avt_03", thumb: "/formations/aviation/avt_03.png", iconSize: 1 },
    { id: "avt_04", thumb: "/formations/aviation/avt_04.png", iconSize: 1 },
    { id: "avt_05", thumb: "/formations/aviation/avt_05.png", iconSize: 1 },
  ],
  "UAV": [
    { id: "uav_01", thumb: "/formations/uav/uav_01.png", iconSize: 1 },
    { id: "uav_02", thumb: "/formations/uav/uav_02.png", iconSize: 1 },
    { id: "uav_03", thumb: "/formations/uav/uav_03.png", iconSize: 1 },
  ],
  "Air_base": [
    { id: "airbase_01", thumb: "/formations/air_base/airbase_01.png", iconSize: 1 },
    { id: "airbase_02", thumb: "/formations/air_base/airbase_02.png", iconSize: 1 },
  ],
  "GBAD": [
    { id: "gbad_01", thumb: "/formations/gbad/gbad_01.png", iconSize: 1 },
    { id: "gbad_02", thumb: "/formations/gbad/gbad_02.png", iconSize: 1 },
    { id: "gbad_03", thumb: "/formations/gbad/gbad_03.png", iconSize: 1 },
    { id: "gbad_04", thumb: "/formations/gbad/gbad_04.png", iconSize: 1 },
    { id: "gbad_05", thumb: "/formations/gbad/gbad_05.png", iconSize: 1 },
    { id: "gbad_06", thumb: "/formations/gbad/gbad_06.png", iconSize: 1 },
    { id: "gbad_07", thumb: "/formations/gbad/gbad_07.png", iconSize: 1 },
    { id: "gbad_08", thumb: "/formations/gbad/gbad_08.png", iconSize: 1 },
    { id: "gbad_09", thumb: "/formations/gbad/gbad_09.png", iconSize: 1 },
    { id: "gbad_10", thumb: "/formations/gbad/gbad_10.png", iconSize: 1 },
  ],
  "Combat Engineer": [
    { id: "eng_01", thumb: "/formations/combat_engineer/eng_01.png", iconSize: 1 },
    { id: "eng_02", thumb: "/formations/combat_engineer/eng_02.png", iconSize: 1 },
    { id: "eng_03", thumb: "/formations/combat_engineer/eng_03.png", iconSize: 1 },
    { id: "eng_04", thumb: "/formations/combat_engineer/eng_04.png", iconSize: 1 },
    { id: "eng_05", thumb: "/formations/combat_engineer/eng_05.png", iconSize: 1 },
    { id: "eng_06", thumb: "/formations/combat_engineer/eng_06.png", iconSize: 1 },
    { id: "eng_07", thumb: "/formations/combat_engineer/eng_07.png", iconSize: 1 },
    { id: "eng_08", thumb: "/formations/combat_engineer/eng_08.png", iconSize: 1 },
    { id: "eng_09", thumb: "/formations/combat_engineer/eng_09.png", iconSize: 1 },
    { id: "eng_10", thumb: "/formations/combat_engineer/eng_10.png", iconSize: 1 },
  ],
  "Construction": [
    { id: "con_01", thumb: "/formations/construction/con_01.png", iconSize: 1 },
    { id: "con_02", thumb: "/formations/construction/con_02.png", iconSize: 1 },
  ],
  "Command Support": [
    { id: "cms_01", thumb: "/formations/command_support_ew/cms_01.png", iconSize: 1 },
    { id: "cms_02", thumb: "/formations/command_support_ew/cms_02.png", iconSize: 1 },
    { id: "cms_03", thumb: "/formations/command_support_ew/cms_03.png", iconSize: 1 },
    { id: "cms_04", thumb: "/formations/command_support_ew/cms_04.png", iconSize: 1 },
    { id: "cms_05", thumb: "/formations/command_support_ew/cms_05.png", iconSize: 1 },
    { id: "cms_06", thumb: "/formations/command_support_ew/cms_06.png", iconSize: 1 },
    { id: "cms_07", thumb: "/formations/command_support_ew/cms_07.png", iconSize: 1 },
    { id: "cms_08", thumb: "/formations/command_support_ew/cms_08.png", iconSize: 1 },
    { id: "cms_09", thumb: "/formations/command_support_ew/cms_09.png", iconSize: 1 },
    { id: "cms_10", thumb: "/formations/command_support_ew/cms_10.png", iconSize: 1 },
  ],
  "Transmission": [
    { id: "trn_01", thumb: "/formations/transmission/trn_01.png", iconSize: 1 },
    { id: "trn_02", thumb: "/formations/transmission/trn_02.png", iconSize: 1 },
    { id: "trn_03", thumb: "/formations/transmission/trn_03.png", iconSize: 1 },
    { id: "trn_04", thumb: "/formations/transmission/trn_04.png", iconSize: 1 },
    { id: "trn_05", thumb: "/formations/transmission/trn_05.png", iconSize: 1 },
    { id: "trn_06", thumb: "/formations/transmission/trn_06.png", iconSize: 1 },
    { id: "trn_07", thumb: "/formations/transmission/trn_07.png", iconSize: 1 },
    { id: "trn_08", thumb: "/formations/transmission/trn_08.png", iconSize: 1 },
    { id: "trn_09", thumb: "/formations/transmission/trn_09.png", iconSize: 1 },
    { id: "trn_10", thumb: "/formations/transmission/trn_10.png", iconSize: 1 },
    { id: "trn_11", thumb: "/formations/transmission/trn_11.png", iconSize: 1 },
    { id: "trn_12", thumb: "/formations/transmission/trn_12.png", iconSize: 1 },
  ],
  "Command, Transmission and EW": [
    { id: "ctew_01", thumb: "/formations/command_transmission_ew/ctew_01.png", iconSize: 1 },
    { id: "ctew_02", thumb: "/formations/command_transmission_ew/ctew_02.png", iconSize: 1 },
    { id: "ctew_03", thumb: "/formations/command_transmission_ew/ctew_03.png", iconSize: 1 },
    { id: "ctew_04", thumb: "/formations/command_transmission_ew/ctew_04.png", iconSize: 1 },
    { id: "ctew_05", thumb: "/formations/command_transmission_ew/ctew_05.png", iconSize: 1 },
  ],
  "Logistics": [
    { id: "logi_01", thumb: "/formations/logistics/logi_01.png", iconSize: 1 },
    { id: "logi_02", thumb: "/formations/logistics/logi_02.png", iconSize: 1 },
    { id: "logi_03", thumb: "/formations/logistics/logi_03.png", iconSize: 1 },
    { id: "logi_04", thumb: "/formations/logistics/logi_04.png", iconSize: 1 },
    { id: "logi_05", thumb: "/formations/logistics/logi_05.png", iconSize: 1 },
    { id: "logi_06", thumb: "/formations/logistics/logi_06.png", iconSize: 1 },
    { id: "logi_07", thumb: "/formations/logistics/logi_07.png", iconSize: 1 },
    { id: "logi_08", thumb: "/formations/logistics/logi_08.png", iconSize: 1 },
    { id: "logi_09", thumb: "/formations/logistics/logi_09.png", iconSize: 1 },
    { id: "logi_10", thumb: "/formations/logistics/logi_10.png", iconSize: 1 },
    { id: "logi_11", thumb: "/formations/logistics/logi_11.png", iconSize: 1 },
    { id: "logi_12", thumb: "/formations/logistics/logi_12.png", iconSize: 1 },
    { id: "logi_13", thumb: "/formations/logistics/logi_13.png", iconSize: 1 },
  ],
  "Transportation": [
    { id: "trsp_01", thumb: "/formations/transportation/trsp_01.png", iconSize: 1 },
    { id: "trsp_02", thumb: "/formations/transportation/trsp_02.png", iconSize: 1 },
    { id: "trsp_03", thumb: "/formations/transportation/trsp_03.png", iconSize: 1 },
    { id: "trsp_04", thumb: "/formations/transportation/trsp_04.png", iconSize: 1 },
    { id: "trsp_05", thumb: "/formations/transportation/trsp_05.png", iconSize: 1 },
    { id: "trsp_06", thumb: "/formations/transportation/trsp_06.png", iconSize: 1 },
  ],
  "Maintenance": [
    { id: "mnt_01", thumb: "/formations/maintenance/mnt_01.png", iconSize: 1 },
    { id: "mnt_02", thumb: "/formations/maintenance/mnt_02.png", iconSize: 1 },
    { id: "mnt_03", thumb: "/formations/maintenance/mnt_03.png", iconSize: 1 },
    { id: "mnt_04", thumb: "/formations/maintenance/mnt_04.png", iconSize: 1 },
    { id: "mnt_05", thumb: "/formations/maintenance/mnt_05.png", iconSize: 1 },
  ],
  "Medical": [
    { id: "med_01", thumb: "/formations/medical/med_01.png", iconSize: 1 },
    { id: "med_02", thumb: "/formations/medical/med_02.png", iconSize: 1 },
    { id: "med_03", thumb: "/formations/medical/med_03.png", iconSize: 1 },
    { id: "med_04", thumb: "/formations/medical/med_04.png", iconSize: 1 },
    { id: "med_05", thumb: "/formations/medical/med_05.png", iconSize: 1 },
  ],
  "Military Security": [
    { id: "ms_01", thumb: "/formations/military_security/ms_01.png", iconSize: 1 },
    { id: "ms_02", thumb: "/formations/military_security/ms_02.png", iconSize: 1 },
    { id: "ms_03", thumb: "/formations/military_security/ms_03.png", iconSize: 1 },
    { id: "ms_04", thumb: "/formations/military_security/ms_04.png", iconSize: 1 },
    { id: "ms_05", thumb: "/formations/military_security/ms_05.png", iconSize: 1 },
  ],
  "NBC Defense": [
    { id: "nbc_01", thumb: "/formations/nbc_defense/nbc_01.png", iconSize: 1 },
    { id: "nbc_02", thumb: "/formations/nbc_defense/nbc_02.png", iconSize: 1 },
    { id: "nbc_03", thumb: "/formations/nbc_defense/nbc_03.png", iconSize: 1 },
    { id: "nbc_04", thumb: "/formations/nbc_defense/nbc_04.png", iconSize: 1 },
    { id: "nbc_05", thumb: "/formations/nbc_defense/nbc_05.png", iconSize: 1 },
    { id: "nbc_06", thumb: "/formations/nbc_defense/nbc_06.png", iconSize: 1 },
    { id: "nbc_07", thumb: "/formations/nbc_defense/nbc_07.png", iconSize: 1 },
    { id: "nbc_08", thumb: "/formations/nbc_defense/nbc_08.png", iconSize: 1 },
    { id: "nbc_09", thumb: "/formations/nbc_defense/nbc_09.png", iconSize: 1 },
    { id: "nbc_10", thumb: "/formations/nbc_defense/nbc_10.png", iconSize: 1 },
  ],
  "Special Forces": [
    { id: "sf_01", thumb: "/formations/special_forces/sf_01.png", iconSize: 1 },
    { id: "sf_02", thumb: "/formations/special_forces/sf_02.png", iconSize: 1 },
    { id: "sf_03", thumb: "/formations/special_forces/sf_03.png", iconSize: 1 },
    { id: "sf_04", thumb: "/formations/special_forces/sf_04.png", iconSize: 1 },
    { id: "sf_05", thumb: "/formations/special_forces/sf_05.png", iconSize: 1 },
    { id: "sf_06", thumb: "/formations/special_forces/sf_06.png", iconSize: 1 },
    { id: "sf_07", thumb: "/formations/special_forces/sf_07.png", iconSize: 1 },
    { id: "sf_08", thumb: "/formations/special_forces/sf_08.png", iconSize: 1 },
    { id: "sf_09", thumb: "/formations/special_forces/sf_09.png", iconSize: 1 },
    { id: "sf_10", thumb: "/formations/special_forces/sf_10.png", iconSize: 1 },
  ],
  "Military Justice": [
    { id: "mj_01", thumb: "/formations/military_justice/mj_01.png", iconSize: 1 },
  ],

  
};
